server/main/urls.py
from django.urls import path
from .views import (
    contacts_view, about_view, main_view
)


app_name = "main"


urlpatterns = [
    path('contacts/', contacts_view, name="contacts"),
    path('about/', about_view, name="about"),
    path('', main_view, name="index"),
]

server/products/urls.py
from django.urls import path
from .views import (
    list_view, detail_view
)


app_name="products"


urlpatterns = [
    path('<int:pk>/', detail_view, name="detail"),
    path('', list_view, name="index"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('main.urls')),
]

server/main/models.py
from django.db import models

# Create your models here.

server/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

server/main/views.py
import json
from django.template import Template, Context
from django.template.loader import get_template, render_to_string
from django.shortcuts import render
from django.http import HttpResponse


def main_view(request):
    # template = Template(
    #     'Hello {{ name }}'
    # )
    # context = Context({
    #     'name': 'Anton'
    # })
    # response_string = template.render(context)

    # template = get_template('main/index.html')

    # context = {
    #     'title': 'This is a main page',
    #     'subtitle': 'First django page',
    #     'username': request.user,
    # }

    # response_string = template.render(context)

    with open('data.json', 'r') as file:
        products = json.load(file)

    response_string = render_to_string(
        'main/index.html',
        {
            'title': 'This is a main page',
            'subtitle': 'First django page',
            # 'username': request.user,
            'username': 'anton',
            'products':  products.get('products') or [],
            'is_active': True
        }
    )

    # return render(request, 'main/index.html')
    return HttpResponse(response_string)


def contacts_view(request):
    return render(
        request, 
        'main/contacts.html',
        {
            'contacts': [
                '8900007500',
                '8900007501',
                '8900007502',
                '8900007500',
                '8900007501',
                '8900007502',
                '8900007500',
                '8900007501',
                '8900007502',
            ]
        }
    )


def about_view(request):
    return render(
        request, 
        'main/about.html',
        {
            'text': 'Несмотря на сложности, гидродинамический удар гасит эллиптический погранслой.'
        }
    )

server/products/views.py
import json
from django.shortcuts import (
    render, get_list_or_404, get_object_or_404
)

from .models import Product


def list_view(request):
    # with open('data.json', 'r') as file:
    #     context = json.load(file)

    # return render(
    #     request, 
    #     'products/list.html',
    #     {
    #         'products': context.get('products') or []
    #     }
    # )
    return render(
        request,
        'products/list.html',
        {
            # 'products': Product.objects.all()
            'products': get_list_or_404(Product)
        }
    )


def detail_view(request, pk):
    # with open('data.json', 'r') as file:
    #     context = json.load(file)

    # products = context.get('products')

    # return render(
    #     request, 
    #     'products/detail.html',
    #     {
    #         'object': products[pk] if len(products) > pk else ''
    #     }
    # )
    return render(
        request,
        'products/detail.html',
        {
            # 'object': Product.objects.get(id=pk)
            'object': get_object_or_404(Product, id=pk)
        }
    )

server/main/templates/main/about.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <h1>
        This is about page
    </h1>
    <ul>
        <li>
            <a href="/">Главня</a>
            <a href="/contacts/">Контакты</a>
            <a href="/about/">О проекте</a>
        </li>
    </ul>
</body>
</html>

server/main/templates/main/contacts.html
{% extends 'master.html' %}

{% block page_title %}
Contacts page
{% endblock %}

{% block page_content %}
<h1>
    This is contacts page
</h1>
<ul>
    {% for itm in contacts|slice:"0:3" %}
    <li>{{ itm }}</li>
    {% endfor %}
</ul>
{% endblock %}

server/main/templates/main/index.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %}
Main page
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'main/index.css' %}">
{% endblock %}

{% block page_content %}
<h1 class="page__title">
    {{ title }}
</h1>
<h2 class="page__subtitle">
    {{ subtitle }}
</h2>
{% if is_active %}
<h3>
    {{ username|title }}
</h3>
{% else %}
<span>
    User is not active
</span>
{% endif %}

<ul class="products-list">
    {% for itm in products|slice:"0:2" %}
        <li class="products-list__item">
            {{ itm.name }}
        </li>
    {% endfor %}
</ul>
{% endblock %}

server/products/templates/products/detail.html
{% extends 'master.html' %}

{% block page_title %}
{{ object }}
{% endblock %}

{% block page_content %}
    {% if object %}
        <h1 class="object__name">
            {{ object.name }}
        </h1>
        <span class="object__description">
            {{ object.description }}
        </span>

    {% else %}
        Product does not exists
    {% endif %}
{% endblock %}

server/products/templates/products/list.html
{% extends 'master.html' %}

{% block page_title %}
Products list page
{% endblock %}

{% block page_content %}
<ul class="products-list">
    {% for itm in products %}
    <li class="products-list__item">
        <!-- <a href="{{ forloop.counter0 }}" class="products-list__item-link">
        </a> -->
        <a class="products-list__item-link" href="{% url 'products:detail' pk=itm.id %}">
                {{ itm.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

server/server/templates/master.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    
    <title>
        {% block page_title %}{% endblock %}
    </title>
    {% block page_styles %}{% endblock %}
</head>
<body>

    <ul>
        <li>
            <a href="{% url 'main:index' %}">Главня</a>
        </li>
        <li>            
            <a href="{% url 'products:index' %}">Каталог</a>
        </li>
        <li>
            <a href="{% url 'main:contacts' %}">Контакты</a>
        </li>
        <li>
            <a href="{% url 'main:about' %}">О проекте</a>
        </li>
    </ul>
    
    {% block page_content %}
    {% endblock %}
    
</body>
</html>